"""
This is the urls.py file for the habitTracker application in the Django project.

It is responsible for defining the URL routing for the habitTracker application. 
This includes mapping URL patterns to the appropriate view functions or viewsets.

The file uses Django's DefaultRouter to automatically generate the URL conf for the 
TaskViewSet and HabitTrackerViewSet viewsets. The generated URL conf includes routes 
for the standard set of list, create, retrieve, update, and delete operations.
"""

# Import the necessary modules from Django and Django REST Framework
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import TaskViewSet, HabitTrackerViewSet, WellnessSnapshotViewSet, GoalViewSet

# Create a DefaultRouter instance
router = DefaultRouter()

# Register the TaskViewSet with the router under the base URL 'tasks'
router.register(r'tasks', TaskViewSet)

# Register the HabitTrackerViewSet with the router under the base URL 'habitTrackers'
router.register(r'habitTrackers', HabitTrackerViewSet)

router.register(r'snapshots', WellnessSnapshotViewSet)

router.register(r'goals', GoalViewSet )
# Define the URL patterns for the habitTracker application
# The include function is used to include the URL conf generated by the router
urlpatterns = [
    path('', include(router.urls)),
]