# Generated by Django 5.0.6 on 2024-05-22 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HabitTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_completed_percentage', models.FloatField(default=0.0)),
                ('weekly_completed_percentage', models.FloatField(default=0.0)),
                ('lifetime_completed_percentage', models.FloatField(default=0.0)),
                ('mentorPrompt', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('habit_tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habitTracker.habittracker')),
            ],
        ),
        migrations.CreateModel(
            name='DailyCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('daily_completed_percentage', models.FloatField(default=0.0)),
                ('habit_tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habitTracker.habittracker')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('completed', models.BooleanField(default=False)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habitTracker.goal')),
                ('habit_tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habitTracker.habittracker')),
            ],
        ),
    ]
