# Generated by Django 5.0.6 on 2024-06-07 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitTracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='goal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='habitTracker.goal'),
        ),
        migrations.AlterField(
            model_name='task',
            name='habit_tracker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='habitTracker.habittracker'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='MentorConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personality_prompt', models.CharField(max_length=300, null=True)),
                ('communication_style', models.CharField(blank=True, choices=[('motivational', 'Motivational: Providing uplifting messages to inspire action.'), ('problem-solving', 'Problem-Solving: Offering practical strategies to overcome challenges.'), ('collaborative', 'Collaborative: Encouraging user participation in decision-making.'), ('reflective', 'Reflective: Promoting introspection and self-discovery through questions.')], max_length=255, null=True)),
                ('language_preference', models.CharField(blank=True, choices=[('informative', 'Informative: Providing factual and educational content.'), ('supportive', 'Supportive: Delivering empathetic and comforting messages.'), ('encouraging', 'Encouraging: Offering words of empowerment and positivity.'), ('assertive', 'Assertive: Providing firm guidance and direction for accountability.')], max_length=255, null=True)),
                ('habit_tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habitTracker.habittracker')),
            ],
        ),
    ]
