# Generated by Django 5.0 on 2023-12-28 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitTracker', '0002_task_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habittracker',
            name='completed',
        ),
        migrations.AddField(
            model_name='habittracker',
            name='completed_percentage',
            field=models.FloatField(default=0.0),
        ),
    ]
