# Generated by Django 5.0 on 2023-12-28 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitTracker', '0003_remove_habittracker_completed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habittracker',
            old_name='completed_percentage',
            new_name='daily_completed_percentage',
        ),
        migrations.AddField(
            model_name='habittracker',
            name='longterm_completed_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='DailyCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('daily_completed_percentage', models.FloatField(default=0.0)),
                ('habit_tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habitTracker.habittracker')),
            ],
        ),
    ]
