# Generated by Django 5.0 on 2023-12-28 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitTracker', '0004_rename_completed_percentage_habittracker_daily_completed_percentage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('journal_entry', models.TextField()),
                ('habit_tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habitTracker.habittracker')),
            ],
        ),
    ]
