# Generated by Django 5.0 on 2023-12-29 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitTracker', '0005_dailyentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='habittracker',
            name='journal_entry',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='DailyEntry',
        ),
    ]
