# Generated by Django 5.0 on 2023-12-31 21:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitTracker', '0006_habittracker_journal_entry_delete_dailyentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='WellnessSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('habit_tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habitTracker.habittracker')),
            ],
        ),
    ]
