# Generated by Django 5.0 on 2024-01-01 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitTracker', '0008_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='habittracker',
            name='mentor',
            field=models.TextField(blank=True, null=True),
        ),
    ]
