# Generated by Django 5.0 on 2024-01-01 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habitTracker', '0009_habittracker_mentor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habittracker',
            old_name='mentor',
            new_name='mentorPrompt',
        ),
    ]
