# Generated by Django 5.0 on 2024-01-06 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitTracker', '0010_rename_mentor_habittracker_mentorprompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habitTracker.goal')),
            ],
        ),
    ]
