# Generated by Django 5.0 on 2024-01-07 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habitTracker', '0011_progressentry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProgressEntry',
        ),
    ]
